name: loc_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  flutter:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
